<?php ?>

<!--
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Pos
 * @author    Webkul
 * @copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
-->

<script type="text/x-magento-init">
    {
        "*": {
            "outletPost" : {},
            "outletLegacy" : {},
            "outletCheckboxTree" : {}
        }
    }
</script>
<script type="text/javascript">
    require([
        "jquery",
        "prototype"
    ], function(jQuery){

        jQuery(document).ajaxSuccess(function (event, xhr, settings)  {
            if (settings.url.match(/pos\/outlet\/validate/g) || settings.url.match(/pos\/cashier\/validate/g))  {
                if (xhr.responseJSON.error)  {
                    jQuery("html, body").scrollTop(jQuery("body").find("#messages").offset().top-100);
                }
            }
        });

        jQuery(document).ready(function(){
            jQuery(".admin__data-grid-loading-mask").hide();
        });

    });
</script>
