<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!-- <?php if ($block->getTitle()): ?>
    <h3><?= $escaper->escapeHtml($block->getTitle()) ?></h3>
<?php endif ?> -->
<?php if (!empty($tabs)): ?>
<div id="<?=  $escaper->escapeHtml($block->getId()) ?>">
<ul  class="tabs-horiz">
    <?php foreach ($tabs as $_tab): ?>
        <?php $_tabClass = 'tab-item-link ' .
        $block->getTabClass($_tab) . ' '
        . (preg_match('/\s?ajax\s?/', $_tab->getClass()) ? 'notloaded' : '') ?>
        <?php $_tabType = (!preg_match('/\s?ajax\s?/', $_tabClass) && $block->getTabUrl($_tab) != '#') ? 'link' : '' ?>
        <?php $_tabHref = $block->getTabUrl($_tab) == '#' ?
        '#' . $block->getTabId($_tab) . '_content' : $block->getTabUrl($_tab) ?>
    <li>
        <a href="<?= $escaper->escapeUrl($_tabHref) ?>" id="<?= $escaper->escapeHtml($block->getTabId($_tab)) ?>" 
        title="<?= $escaper->escapeHtml($block->getTabTitle($_tab)) ?>"
        class="<?= $escaper->escapeHtml($_tabClass) ?>" data-tab-type="<?= $escaper->escapeHtml($_tabType) ?>">
            <span>
                <span class="changed" 
                title="<?= /*@noEscape*/ __('The information in this tab has been changed.') ?>"></span>
                <span class="error" 
                title="<?= /*@noEscape*/ __('This tab contains invalid data. Please resolve this before saving.') ?>">
                </span>
                <span class="loader" title="<?= /*@noEscape*/ __('Loading...') ?>"></span>
                <?= $escaper->escapeHtml($block->getTabLabel($_tab)) ?>
            </span>
        </a>
        <div id="<?=  $escaper->escapeHtml($block->getTabId($_tab)) ?>_content" 
        style="display:none"><?= /* @noEscape */ $block->getTabContent($_tab) ?></div>
    </li>
    <?php endforeach; ?>
</ul>
</div>
<script>
require(["jquery","mage/backend/tabs"], function($){
    $(function() {
        $('#<?= /* @noEscape */ $block->getId() ?>').tabs({
            active: '<?= /* @noEscape */ $block->getActiveTabId() ?>',
            destination: '#<?= /* @noEscape */ $block->getDestElementId() ?>',
            shadowTabs: <?= /* @noEscape */ $block->getAllShadowTabs() ?>
        });
    });
});
</script>
<?php endif; ?>
