<!--
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Pos
 * @author    Webkul
 * @copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
-->
<html lang="<?= /* @noEscape */ $escaper->escapeHtml($block->getCurrentlocale()); ?>">
<head>
    <title><?= /* @noEscape */ __("Customer Data"); ?></title>
</head>
<body>
