<!--
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Pos
 * @author    Webkul
 * @copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
-->
<?php  ?>
<style>
   table {
    margin:16px 0;
   }

   table td, table th {
       text-align:left;
       padding:16px;
       margin:5px;
       vertical-align:top;
       word-wrap: break-word;
   }

   .admin__data-grid-action-export{
       display: none;
   }

   .main-title, h3{
       text-align: center;
       padding: 8px;
   }
</style>
